### ISSUE TITLE
deploying in preview mode: info files

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#457]
i tried deploying preview today and got the following error. i can't tell if it's a problem with bb36.info.xml or bb32.info.xml or whatever comes after them, but neither seem to be on the preview branch.

ERROR:import:info file does not exist: bb36.info.xml

ERROR:import:info file does not exist: bb32.info.xml

ERROR:import:info file does not exist: 

Traceback (most recent call last):

  File https://contactmonkey.com/api/v1/tracker?cm_session=0e6df5b0-106d-4391-9b47-4c820188d70a&cm_type=link&cm_link=f804c8d4-6fe8-4255-a65c-60e12dbe5204&cm_destination=http://import.py, line 498, in <module>

    main()

  File https://contactmonkey.com/api/v1/tracker?cm_session=0e6df5b0-106d-4391-9b47-4c820188d70a&cm_type=link&cm_link=57092b49-f647-46c6-aad1-192b73bb32dc&cm_destination=http://import.py, line 494, in main

    importer.import_data()

  File https://contactmonkey.com/api/v1/tracker?cm_session=0e6df5b0-106d-4391-9b47-4c820188d70a&cm_type=link&cm_link=76493857-7c0f-41cb-bd53-6dab2a6cfca9&cm_destination=http://import.py, line 68, in import_data

    self.process_relationships()

  File https://contactmonkey.com/api/v1/tracker?cm_session=0e6df5b0-106d-4391-9b47-4c820188d70a&cm_type=link&cm_link=7e0268d6-7806-49f2-a8a8-d0c8fbbb7164&cm_destination=http://import.py, line 114, in process_relationships

    self.process_relationship(entry)

  File https://contactmonkey.com/api/v1/tracker?cm_session=0e6df5b0-106d-4391-9b47-4c820188d70a&cm_type=link&cm_link=c07ab92c-edcb-4fa8-af37-7523848b7b8d&cm_destination=http://import.py, line 119, in process_relationship

    obj.objects_from_same_matrix.extend(self.objects_for_id_string(entry.same_matrix_ids))

AttributeError: 'NoneType' object has no attribute 'objects_from_same_matrix'

python stderr: Nothing written

**Comment by ba001** [comment]
i think what's happening is that the system expects the info files to exist. do we want to change this so that it shouldn't? or should we just put up dummy info files before they've been completed?

**Comment by ba001** [comment]
found the info files and added them. now i'm getting this:

ERROR:import:info file does not exist: 
Traceback (most recent call last):
  File "import.py", line 498, in <module>
    main()
  File "import.py", line 494, in main
    importer.import_data()
  File "import.py", line 68, in import_data
    self.process_relationships()
  File "import.py", line 114, in process_relationships
    self.process_relationship(entry)
  File "import.py", line 119, in process_relationship
    obj.objects_from_same_matrix.extend(self.objects_for_id_string(entry.same_matrix_ids))
AttributeError: 'NoneType' object has no attribute 'objects_from_same_matrix'
python stderr: Nothing written

**Comment by ba001** [comment]
could this be an issue with the blank entries in blake-relations.csv?

america.k.illbk.01,america.K.P1,america.k,america,,,,,,,
 +america.k.illbk.02,america.K.P2,america.k,america,,,,,,,
 +america.k.illbk.03,america.K.P3,america.k,america,,,,,,,
 +america.k.illbk.04,america.K.P4,america.k,america,,,,,,,
 +america.k.illbk.05,america.K.P5,america.k,america,,,,,,,
 +america.k.illbk.06,america.K.P6,america.k,america,,,,,,,
 +america.k.illbk.07,america.K.P7,america.k,america,,,,,,,
 +america.k.illbk.08,america.K.P8,america.k,america,,,,,,,
 +america.k.illbk.09,america.K.P9,america.k,america,,,,,,,
 +america.k.illbk.10,america.K.P10,america.k,america,,,,,,,
 +america.k.illbk.11,america.K.P11,america.k,america,,,,,,,
 +america.k.illbk.12,america.K.P12,america.k,america,,,,,,,
 +america.k.illbk.13,america.K.P13,america.k,america,,,,,,,
 +america.k.illbk.14,america.K.P14,america.k,america,,,,,,,
 +america.k.illbk.15,america.K.P15,america.k,america,,,,,,,
 +america.k.illbk.16,america.K.P16,america.k,america,,,,,,,
 +america.k.illbk.17,america.K.P17,america.k,america,,,,,,,
 +america.k.illbk.18,america.K.P18,america.k,america,,,,,,,

**Comment by ba001** [comment]
actually it looks like there are other works like that one, so i don't think that's the problem

**Comment by ba001** [comment]
i think one of the commits from february 1 to today is the problem

**Comment by joeafletch** [comment]
@ba001 Yeah, I'm not sure I did anything differently with bb11-12, bb32, and bb36 from what I did when I added the Thel copies to Preview. The info files seem fine--3 out of the 4 of them are dummies in the sense that they don't have the "remarks" or "relations" fields filled in, but that shouldn't be a problem, since their headers look consistent with other already-published info files. And yes, I've only filled in the first four columns on the blake-relations.csv for these four copies, but I did the same thing with the Thel copies.

But I notice that this is the first time we've added typographic editions into the database, which is what the "te" in the descid's and the "TYP" in the dbi's is referring to for bb11, bb12, bb32, and bb36. @nathan-rice Could it be the code/import scripts isn't set up to accommodate this new medium? There's a "Typographic Editions" category set up on the main toc, but we haven't yet published any works in this category (but we have several that we want to put up on the London/Preview site).

**Comment by nathan-rice** [comment]
The problem here is that you're referring to these files in one place as 'bb11.a.typ.03' and in another as 'bb11.a.te.01'

**Comment by ba001** [comment]
yeah, i thought that might be the problem. i fixed the BADs to read *te*, but i'm still getting the error

**Comment by nathan-rice** [comment]
Double check that .typ has been replaced everywhere, then push those changes to the preview branch and I'll take a second look later today.

**Comment by ba001** [comment]
@joeafletch joe, the dbi's need to retain the TYP, right? only desc id's need to change to 'te'? 

do those have to be the same, @nathan-rice ?

**Comment by joeafletch** [comment]
@ba001 @nathan-rice Yes, dbi's need to retain TYP. The problem may be that the .typ is there for all the line transcriptions ("n=" in the <phystext>), which get identified according to desc id #s. I started to fix it, but realized it was going to take long time (bb36 has 71 objects and a ton of transcription), so I'm holding off until we're sure that's the problem.

**Comment by ba001** [comment]
@joeafletch joe, i just did a quick regex to replace all the 'typ's in the line transcriptions

still getting the error, though

**Comment by joeafletch** [comment]
@ba001 Thanks. Maybe the problem is that I haven't made entries in the blake-relations.csv for all 71 objects in bb32 that are listed in the BAD? Right now there is only one object listed. I'll make the change and let you know when I'm done.

**Comment by ba001** [comment]
hmm, i don't think that's the problem because before we've been able to index BADs without adding any of their objects to blake-relations.csv. haven't we?

**Comment by joeafletch** [comment]
Not sure.

**Comment by ba001** [comment]
ok, let me put them in quickly and see

**Comment by joeafletch** [comment]
I just added them so it's ready to go

**Comment by joeafletch** [comment]
(I committed and synced as well)

**Comment by ba001** [comment]
nope, that didn't fix it, either

**Comment by ba001** [comment]
@joeafletch noticed that the entries for thel.e in blake-relations don't match the desc id's in the bad

**Comment by ba001** [comment]
i changed thel.e desc id's. they were reading 01-02, 02-03... i made them 01, 02, 03, but i'm still getting the error unfortunately

**Comment by ba001** [comment]
@nathan-rice i'm pretty sure all the blake-relation desc id's in question match the BAD id's now, so you can take a look whenever you get a chance

**Comment by joeafletch** [comment]
@ba001 I'm assuming the desc id's were wrong in the BAD and not in blake-relations, but thanks for making the changes in any case.

**Comment by ba001** [comment]
yeah, i meant to ask about that. let me know if it's the other way around. i can reverse it

**Comment by ba001** [comment]
i looked at the line transcriptions to tell

**Comment by joeafletch** [comment]
no, desc id's should never have hyphenated numbers, so did right to change the BAD; only dbi's have the hyphenated numbers.

**Comment by nathan-rice** [comment]
These are the problem:

thel.a-proof.illbk.01
thel.a-proof.illbk.02
thel.a-proof.illbk.03
thel.a-proof.illbk.04
thel.a-proof.illbk.05

None of the -proof desc_ids exist in the bads being imported.

**Comment by ba001** [comment]
looks like we don't have a BAD for it. but i had tried taking those entries out (f8342776a9f810ad92bb0bb52de65a115240a98b) and that didn't work

**Comment by ba001** [comment]
hmm, well, i tried taking it out again. this time it worked. i think i'd made other corrections after the first attempt, and then didn't try again after i'd made those other corrections. all is well now. @joeafletch i've taken out thel.a-proof from blake-relations. we can it back in once we get the BAD for it up

**Comment by ba001** [comment]
@nathan-rice i just realized we have a procedural issue here. i'm going to be cherry picking BADs from the preview branch to commit to master as we publish them. but i can't cherry pick parts of blake-relations.csv. is it possible to make it so that any objects (lines) from blake-relations.csv that don't have corresponding BADS don't get processed?

**Comment by ba001** [comment]
or just allow for null relationships

**Comment by joeafletch** [comment]
Okay, I didn't realize that adding entries to the blake-relations.csv without a corresponding BAD would cause errors. We're waiting on the BAD for thel.a-proof, but I wanted to add the entries for it so that Grant could edit/complete all the thel columns on blake-relations in the meantime, since we're going to publish those added copies this month. So yeah, if it's possible to make it so that lines without corresponding BADs don't get processed, that would be good.

**Comment by ba001** [comment]
@nathan-rice just wanted to remind you about this. our publication process would be a lot easier if blake-relations.csv could be processed as a master table containing references to objects that we aren't publishing yet.

**Comment by nathan-rice** [comment]
I never forgot about it, I'm just occupied refactoring some of the particularly bad code on the site.

**Comment by ba001** [comment]
ok, thanks.

**Comment by nathan-rice** [comment]
This issue should be fixed in the refactor branch, give it a spin and make sure it works for you.

**Comment by ba001** [comment]
hmm, i can't test the indexing (importing) locally because of the mac issue, so i'm just going to merge the refactor branch into master and test on development. i'm sure it'll be fine, but if we have to, i can undo the merge

**Comment by ba001** [comment]
@queryluke luke, i'm trying to test the refactoring on qa. since i couldn't select the refactor branch on qa, i merged it into master. now, when i try to deploy, i get:

Your branch is up-to-date with 'origin/python26'.
Already up-to-date.
Removing blakearchive/static/js/main.js
Auto-merging blakearchive/services.py
CONFLICT (content): Merge conflict in blakearchive/services.py
Removing blakearchive/import_stats.out
Auto-merging blakearchive/import.py
Automatic merge failed; fix conflicts and then commit the result.
blakearchive/services.py: needs merge
cd ../archive; git checkout master; git pull origin master; git checkout python26; git pull; git merge --no-ff -m 'Merge master into python26' master; git push origin python26; git checkout master; stderr: Already on 'master'
From https://github.com/blakearchive/archive
 * branch            master     -> FETCH_HEAD
   be1f923..a64747b  master     -> origin/master
Switched to branch 'python26'
From https://github.com/blakearchive/archive
   600d76e..86d76a0  refactor   -> origin/refactor
Everything up-to-date
error: you need to resolve your current index first

**Comment by ba001** [comment]
@queryluke here's the beginning of the error:
BUG [7ebc4785] 	Switched to branch 'master'
DEBUG [7ebc4785] 	Your branch is up-to-date with 'origin/master'.
DEBUG [7ebc4785] 	From https://github.com/blakearchive/archive
DEBUG [7ebc4785] 	 * branch            master     -> FETCH_HEAD
DEBUG [7ebc4785] 	Already up-to-date.
DEBUG [7ebc4785] 	Switched to branch 'python26'
DEBUG [7ebc4785] 	Your branch and 'origin/python26' have diverged,
DEBUG [7ebc4785] 	and have 15 and 323 different commits each, respectively.
DEBUG [7ebc4785] 	  (use "git pull" to merge the remote branch into yours)
DEBUG [7ebc4785] 	Auto-merging blakearchive/services.py
DEBUG [7ebc4785] 	CONFLICT (content): Merge conflict in blakearchive/services.py
DEBUG [7ebc4785] 	Auto-merging blakearchive/import.py
DEBUG [7ebc4785] 	Automatic merge failed; fix conflicts and then commit the result.
DEBUG [7ebc4785] 	error: Merging is not possible because you have unmerged files.
DEBUG [7ebc4785] 	hint: Fix them up in the work tree, and then use 'git add/rm <file>'
DEBUG [7ebc4785] 	hint: as appropriate to mark resolution and make a commit.
DEBUG [7ebc4785] 	fatal: Exiting because of an unresolved conflict.
DEBUG [7ebc4785] 	To https://github.com/blakearchive/archive.git
DEBUG [7ebc4785] 	 ! [rejected]        python26 -> python26 (non-fast-forward)
DEBUG [7ebc4785] 	error: failed to push some refs to 'https://github.com/blakearchive/archive.git'
DEBUG [7ebc4785] 	hint: Updates were rejected because the tip of your current branch is behind
DEBUG [7ebc4785] 	hint: its remote counterpart. Integrate the remote changes (e.g.
DEBUG [7ebc4785] 	hint: 'git pull ...') before pushing again.
DEBUG [7ebc4785] 	hint: See the 'Note about fast-forwards' in 'git push --help' for details.
DEBUG [7ebc4785] 	error: you need to resolve your current index first
DEBUG [7ebc4785] 	blakearchive/services.py: needs merge

**Comment by queryluke** [comment]
```
DEBUG [7ebc4785] Your branch and 'origin/python26' have diverged,
DEBUG [7ebc4785] and have 15 and 323 different commits each, respectively.
```
Means that at some point you were working on python26 and committed changes, so you'll want to either wipe away your python26 local changes or you can delete the local branch completely and get a fresh copy from origin

**Comment by ba001** [comment]
@queryluke but isn't that error for the qa server? why would deploying have anything to do with my python26 local branch?

**Comment by ba001** [comment]
@queryluke i just tried resetting my local python26 branch. didn't help. i don't think this error has anything to do with my local branches. i'm trying to deploy to qa and getting that error

**Comment by queryluke** [comment]
https://gitlab.lib.unc.edu/blake/archive-deploy/blob/master/config/deploy/qa.rb, Lines 8-16

Specifically, line 11 is "run locally", which means on your machine.

The commands in the "execute block" (line 13) are:

* switch to the archive repo
`cd ../archive`

* checks out master branch
`git checkout master` 
corresponds with 
```
BUG [7ebc4785] Switched to branch 'master'
DEBUG [7ebc4785] Your branch is up-to-date with 'origin/master'.
```

* pull remote changes
`git pull origin master`
corresponds with 
```
DEBUG [7ebc4785] From https://github.com/blakearchive/archive
DEBUG [7ebc4785] * branch master -> FETCH_HEAD
DEBUG [7ebc4785] Already up-to-date.
```

* switch to python26 branch
`git checkout python26`
corresponds with
```
DEBUG [7ebc4785] Switched to branch 'python26'
DEBUG [7ebc4785] Your branch and 'origin/python26' have diverged,
DEBUG [7ebc4785] and have 15 and 323 different commits each, respectively.
DEBUG [7ebc4785] (use "git pull" to merge the remote branch into yours)
```

* pull any python26 changes
`git pull`
causes the error (I think)
```
DEBUG [7ebc4785] Auto-merging blakearchive/services.py
DEBUG [7ebc4785] CONFLICT (content): Merge conflict in blakearchive/services.py
DEBUG [7ebc4785] Auto-merging blakearchive/import.py
DEBUG [7ebc4785] Automatic merge failed; fix conflicts and then commit the result.
```
but it might also be the next command:
 git merge --no-ff -m 'Merge master into python26' master

Capistrano is just automation of a specific set of commands, so if you cd into archive and start running the commands individually, you should be able to pinpoint which command is the issue.

Either way, deleting your local python26 branch should fix it.

**Comment by ba001** [comment]
@queryluke ok, i thought those commands get run on the qa server. i tried deleting my local python26 branch. didn't work. still get the same error message

**Comment by ba001** [comment]
i think i see the issue. there's a merge conflict in services.py:

```
<<<<<<< HEAD

if hasattr(config, "solr") and config.solr == "local":
    blake_object_solr = pysolr.Solr('http://localhost:8983/solr/blake_object')
    blake_copy_solr = pysolr.Solr('http://localhost:8983/solr/blake_copy')
    blake_work_solr = pysolr.Solr('http://localhost:8983/solr/blake_work')
else:
    blake_object_solr = pysolr.Solr('http://ctools-dev.its.unc.edu:8983/solr/blake-object')
    blake_copy_solr = pysolr.Solr('http://ctools-dev.its.unc.edu:8983/solr/blake-copy')
    blake_work_solr = pysolr.Solr('http://ctools-dev.its.unc.edu:8983/solr/blake-work')
=======
blake_object_solr = pysolr.Solr('http://localhost:8983/solr/blake-object')
blake_copy_solr = pysolr.Solr('http://localhost:8983/solr/blake-copy')
blake_work_solr = pysolr.Solr('http://localhost:8983/solr/blake-work')
>>>>>>> master

```

**Comment by ba001** [comment]
@nathan-rice getting an error when trying to deploy to qa:

EBUG [2fd205dc] Command: cd /net/deploy/blake/qa/blake-archive/current/blakearchive && /usr/bin/env python solrimport.py
DEBUG [2fd205dc] 	Traceback (most recent call last):
  File "solrimport.py", line 96, in <module>
    main()
  File "solrimport.py", line 28, in main
    blake_object_solr.delete(q='*:*')
  File "/usr/lib/python2.6/site-packages/pysolr.py", line 780, in delete
DEBUG [2fd205dc] 	    return self._update(m, commit=commit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "/usr/lib/python2.6/site-packages/pysolr.py", line 359, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/usr/lib/python2.6/site-packages/pysolr.py", line 293, in _send_request
    raise SolrError(error_message)
pysolr.SolrError: [Reason: Error 404 Not Found]

**Comment by ba001** [comment]
@nathan-rice nevermind, i had to fix some typos in solrimport.py. you had dashes instead of underscores for blake_object, blake_work, blake_copy in the urls

**Comment by ba001** [comment]
@queryluke @nathan-rice ok, it seemed to finish the importing all right, but now i'm getting an Internal Server Error when trying to access london.lib.unc.edu

**Comment by ba001** [comment]
from David Romani:

errors start at
[Tue Feb 14 14:34:45 2017] [error] [client 172.17.21.241] mod_wsgi (pid=23703): Target WSGI script '/htdocs/wsgi/blake-qa.wsgi' cannot be loaded as Python module.
[Tue Feb 14 14:34:45 2017] [error] [client 172.17.21.241] mod_wsgi (pid=23703): Exception occurred processing WSGI script '/htdocs/wsgi/blake-qa.wsgi'.
[Tue Feb 14 14:34:45 2017] [error] [client 172.17.21.241] Traceback (most recent call last):
[Tue Feb 14 14:34:45 2017] [error] [client 172.17.21.241]   File "/htdocs/wsgi/blake-qa.wsgi", line 3, in <module>
[Tue Feb 14 14:34:45 2017] [error] [client 172.17.21.241]     from run import app as application
[Tue Feb 14 14:34:45 2017] [error] [client 172.17.21.241]   File "/htdocs/webdata/run.py", line 2, in <module>
[Tue Feb 14 14:34:45 2017] [error] [client 172.17.21.241]     from blakearchive import app, models, services, config
[Tue Feb 14 14:34:45 2017] [error] [client 172.17.21.241]   File "/htdocs/webdata/blakearchive/services.py", line 6, in <module>
[Tue Feb 14 14:34:45 2017] [error] [client 172.17.21.241]     if hasattr(config, "solr") and config.solr == "local":
[Tue Feb 14 14:34:45 2017] [error] [client 172.17.21.241] NameError: name 'config' is not defined

**Comment by nathan-rice** [comment]
This was probably caused when you reverted some of the changes I made to the services.py file, but not all of them.  You just need to go back to that file and make sure you re-add the line "import config"

**Comment by queryluke** [comment]
Yep, as nathan said, the top of services.py should look like this
```
import re
import pysolr
from sqlalchemy.sql import func
import config
import models
```

**Comment by ba001** [comment]
ok, it's back up, but it's got no menu: http://london.lib.unc.edu/

**Comment by ba001** [comment]
seeing this error in the console:

GET http://london.lib.unc.edu/static/build/bundle.js 
(index):168

**Comment by queryluke** [comment]
right, there is no `/statis/build/bundle.js`

Did you build the minified javascript using `npm build`?

**Comment by queryluke** [comment]
See https://github.com/blakearchive/archive/issues/185, bundle.js needs to be built and put into the repo

**Comment by ba001** [comment]
ok, do i have to rebuild it every time i make a change to a js file?

**Comment by queryluke** [comment]
if it works like erdman, it will watch the .js files for changes and rebuild when is notices a change

**Comment by ba001** [comment]
hmm, i did the npm install and npm build, but i'm not sure where it placed bundle.js. can't seem to find it. git commit doesn't find any new files

**Comment by nathan-rice** [comment]
The bundle.js file gets built in `/static/build/`. The `npm run-script build` doesn't do a watch, it does a one time build.  In my next pass of the refactor I'll add a build-watch.

It won't automatically be added to git unless you `git add` it.

**Comment by ba001** [comment]
yeah, there is no /static/build/ after i do npm build

**Comment by nathan-rice** [comment]
The command is `npm run-script build`

**Comment by ba001** [comment]
ok, tried that command and got:

Michaels-MacBook-Pro:archive michaelfox$ npm run-script build

> BlakeArchive@0.1.0 build /Users/michaelfox/Sites/blake/archive
> webpack

/Users/michaelfox/Sites/blake/archive/node_modules/webpack/bin/webpack.js:186
		outputOptions.children = options.map(o => o.stats);
		                                       ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 16.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run-script" "build"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! BlakeArchive@0.1.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BlakeArchive@0.1.0 build script 'webpack'.
npm ERR! This is most likely a problem with the BlakeArchive package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get their info via:
npm ERR!     npm owner ls BlakeArchive
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/michaelfox/Sites/blake/archive/npm-debug.log

**Comment by queryluke** [comment]
It's not a mac thing, it worked on my machine

**Comment by ba001** [comment]
had to update node.js

**Comment by ba001** [comment]
ok, it's up now, but i see a couple of problems so far. the sizing of the object view is off. and in the search results, when clicking on a result to preview it, the browser window doesn't adjust properly

**Comment by ba001** [comment]
also, i can't seem to select a handprint from the tabs and make it show in the gallery

**Comment by nathan-rice** [comment]
Please create a refactor tag and create new issues rather than spamming this issue.

**Comment by ba001** [comment]
ok, i added a few to the refactoring project

**Comment by ba001** [comment]
@nathan-rice do you want me to leave the refactored site up on london? or should i revert the merge? @joeafletch, let me know if you'd rather we revert the merge (take down the refactored site) so that we can continue to publish. i'd say we just wait to fix the few bugs in it before publishing anything more

**Comment by nathan-rice** [comment]
It probably won't take me very long to fix any issues, so I doubt unwinding things will be worth the trouble.
